version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: protego-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: protego
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: protego-backend
    restart: always
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/protego
      ALCHEMY_WS_URL: wss://eth-sepolia.g.alchemy.com/v2/YOUR_ALCHEMY_KEY
      PORT: 4000
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: protego-frontend
    restart: always
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata: