services:
  - type: web
    name: protego-backend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker-compose build backend
    startCommand: docker-compose up backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALCHEMY_WS_URL
        sync: false
      - key: FLASHBOTS_RPC_URL
        sync: false
      - key: TENDERLY_API_KEY
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: protego-frontend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker-compose build frontend
    startCommand: docker-compose up frontend
    envVars:
      - key: VITE_API_BASE_URL
        sync: false

  - type: pserv
    name: protego-db
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: docker-compose build db
    startCommand: docker-compose up db
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: admin123
      - key: POSTGRES_DB
        value: protego
